// <auto-generated />
using System;
using Microsoft.EntityFrameworkCore;
using Microsoft.EntityFrameworkCore.Infrastructure;
using Microsoft.EntityFrameworkCore.Metadata;
using Microsoft.EntityFrameworkCore.Migrations;
using Microsoft.EntityFrameworkCore.Storage.ValueConversion;
using PortManagementSystem.DAL.Database;

#nullable disable

namespace PortManagementSystem.DAL.Migrations
{
    [DbContext(typeof(ProgramContext))]
    [Migration("20250428213344_fix")]
    partial class fix
    {
        /// <inheritdoc />
        protected override void BuildTargetModel(ModelBuilder modelBuilder)
        {
#pragma warning disable 612, 618
            modelBuilder
                .HasAnnotation("ProductVersion", "8.0.0")
                .HasAnnotation("Relational:MaxIdentifierLength", 128);

            SqlServerModelBuilderExtensions.UseIdentityColumns(modelBuilder);

            modelBuilder.Entity("PortManagementSystem.DAL.Models.Ship", b =>
                {
                    b.Property<int>("id")
                        .ValueGeneratedOnAdd()
                        .HasColumnType("int");

                    SqlServerPropertyBuilderExtensions.UseIdentityColumn(b.Property<int>("id"));

                    b.Property<DateOnly>("EAT")
                        .HasColumnType("date");

                    b.Property<DateOnly>("EDT")
                        .HasColumnType("date");

                    b.Property<string>("cargoType")
                        .IsRequired()
                        .HasColumnType("nvarchar(max)");

                    b.Property<string>("destination")
                        .IsRequired()
                        .HasColumnType("nvarchar(max)");

                    b.Property<double>("length")
                        .HasColumnType("float");

                    b.Property<string>("name")
                        .IsRequired()
                        .HasColumnType("nvarchar(max)");

                    b.Property<string>("status")
                        .IsRequired()
                        .HasColumnType("nvarchar(max)");

                    b.Property<int?>("terminalId")
                        .HasColumnType("int");

                    b.Property<int>("userId")
                        .HasColumnType("int");

                    b.Property<double>("width")
                        .HasColumnType("float");

                    b.HasKey("id");

                    b.HasIndex("terminalId");

                    b.HasIndex("userId");

                    b.ToTable("Ships");
                });

            modelBuilder.Entity("PortManagementSystem.DAL.Models.Shipment", b =>
                {
                    b.Property<int>("id")
                        .ValueGeneratedOnAdd()
                        .HasColumnType("int");

                    SqlServerPropertyBuilderExtensions.UseIdentityColumn(b.Property<int>("id"));

                    b.Property<int>("shipId")
                        .HasColumnType("int");

                    b.Property<string>("status")
                        .IsRequired()
                        .HasColumnType("nvarchar(max)");

                    b.Property<string>("type")
                        .IsRequired()
                        .HasColumnType("nvarchar(max)");

                    b.HasKey("id");

                    b.HasIndex("shipId");

                    b.ToTable("Shipments");
                });

            modelBuilder.Entity("PortManagementSystem.DAL.Models.ShipsWaiting", b =>
                {
                    b.Property<int>("id")
                        .ValueGeneratedOnAdd()
                        .HasColumnType("int");

                    SqlServerPropertyBuilderExtensions.UseIdentityColumn(b.Property<int>("id"));

                    b.Property<int>("Duration")
                        .HasColumnType("int");

                    b.Property<DateOnly>("EATDate")
                        .HasColumnType("date");

                    b.Property<DateOnly>("EDTDate")
                        .HasColumnType("date");

                    b.Property<string>("cargoType")
                        .IsRequired()
                        .HasColumnType("nvarchar(max)");

                    b.Property<string>("name")
                        .IsRequired()
                        .HasColumnType("nvarchar(max)");

                    b.Property<int>("shipId")
                        .HasColumnType("int");

                    b.Property<string>("status")
                        .IsRequired()
                        .HasColumnType("nvarchar(max)");

                    b.HasKey("id");

                    b.ToTable("shipsWaitingTable");
                });

            modelBuilder.Entity("PortManagementSystem.DAL.Models.TempShip", b =>
                {
                    b.Property<int>("id")
                        .ValueGeneratedOnAdd()
                        .HasColumnType("int");

                    SqlServerPropertyBuilderExtensions.UseIdentityColumn(b.Property<int>("id"));

                    b.Property<DateOnly>("EATDate")
                        .HasColumnType("date");

                    b.Property<DateOnly>("EDTDate")
                        .HasColumnType("date");

                    b.Property<string>("cargoType")
                        .IsRequired()
                        .HasColumnType("nvarchar(max)");

                    b.Property<string>("destination")
                        .IsRequired()
                        .HasColumnType("nvarchar(max)");

                    b.Property<double>("length")
                        .HasColumnType("float");

                    b.Property<string>("name")
                        .IsRequired()
                        .HasColumnType("nvarchar(max)");

                    b.Property<string>("status")
                        .IsRequired()
                        .HasColumnType("nvarchar(max)");

                    b.Property<int?>("tempTerminalId")
                        .HasColumnType("int");

                    b.Property<int>("tempUserId")
                        .HasColumnType("int");

                    b.Property<double>("width")
                        .HasColumnType("float");

                    b.HasKey("id");

                    b.HasIndex("tempTerminalId");

                    b.HasIndex("tempUserId");

                    b.ToTable("TempShips");
                });

            modelBuilder.Entity("PortManagementSystem.DAL.Models.TempShipsWaiting", b =>
                {
                    b.Property<int>("id")
                        .ValueGeneratedOnAdd()
                        .HasColumnType("int");

                    SqlServerPropertyBuilderExtensions.UseIdentityColumn(b.Property<int>("id"));

                    b.Property<int>("Duration")
                        .HasColumnType("int");

                    b.Property<DateOnly>("EATDate")
                        .HasColumnType("date");

                    b.Property<DateOnly>("EDTDate")
                        .HasColumnType("date");

                    b.Property<string>("cargoType")
                        .IsRequired()
                        .HasColumnType("nvarchar(max)");

                    b.Property<string>("name")
                        .IsRequired()
                        .HasColumnType("nvarchar(max)");

                    b.Property<int>("shipId")
                        .HasColumnType("int");

                    b.Property<string>("status")
                        .IsRequired()
                        .HasColumnType("nvarchar(max)");

                    b.HasKey("id");

                    b.HasIndex("shipId");

                    b.ToTable("TempShipsWaiting");
                });

            modelBuilder.Entity("PortManagementSystem.DAL.Models.TempTerminal", b =>
                {
                    b.Property<int>("id")
                        .ValueGeneratedOnAdd()
                        .HasColumnType("int");

                    SqlServerPropertyBuilderExtensions.UseIdentityColumn(b.Property<int>("id"));

                    b.Property<string>("classification")
                        .IsRequired()
                        .HasColumnType("nvarchar(max)");

                    b.Property<string>("status")
                        .IsRequired()
                        .HasColumnType("nvarchar(max)");

                    b.HasKey("id");

                    b.ToTable("TempTerminals");
                });

            modelBuilder.Entity("PortManagementSystem.DAL.Models.Terminal", b =>
                {
                    b.Property<int>("id")
                        .ValueGeneratedOnAdd()
                        .HasColumnType("int");

                    SqlServerPropertyBuilderExtensions.UseIdentityColumn(b.Property<int>("id"));

                    b.Property<string>("classification")
                        .IsRequired()
                        .HasColumnType("nvarchar(max)");

                    b.Property<string>("status")
                        .IsRequired()
                        .HasColumnType("nvarchar(max)");

                    b.HasKey("id");

                    b.ToTable("Terminals");
                });

            modelBuilder.Entity("PortManagementSystem.DAL.Models.User", b =>
                {
                    b.Property<int>("id")
                        .ValueGeneratedOnAdd()
                        .HasColumnType("int");

                    SqlServerPropertyBuilderExtensions.UseIdentityColumn(b.Property<int>("id"));

                    b.Property<byte[]>("PasswordHash")
                        .IsRequired()
                        .HasColumnType("varbinary(max)");

                    b.Property<byte[]>("PasswordSalt")
                        .IsRequired()
                        .HasColumnType("varbinary(max)");

                    b.Property<string>("email")
                        .IsRequired()
                        .HasColumnType("nvarchar(max)");

                    b.Property<string>("role")
                        .IsRequired()
                        .HasColumnType("nvarchar(max)");

                    b.Property<string>("username")
                        .IsRequired()
                        .HasColumnType("nvarchar(max)");

                    b.HasKey("id");

                    b.ToTable("Users");
                });

            modelBuilder.Entity("PortManagementSystem.DAL.Models.Ship", b =>
                {
                    b.HasOne("PortManagementSystem.DAL.Models.Terminal", "terminal")
                        .WithMany("ships")
                        .HasForeignKey("terminalId");

                    b.HasOne("PortManagementSystem.DAL.Models.User", "user")
                        .WithMany("ships")
                        .HasForeignKey("userId")
                        .OnDelete(DeleteBehavior.Cascade)
                        .IsRequired();

                    b.Navigation("terminal");

                    b.Navigation("user");
                });

            modelBuilder.Entity("PortManagementSystem.DAL.Models.Shipment", b =>
                {
                    b.HasOne("PortManagementSystem.DAL.Models.Ship", "ship")
                        .WithMany()
                        .HasForeignKey("shipId")
                        .OnDelete(DeleteBehavior.Cascade)
                        .IsRequired();

                    b.Navigation("ship");
                });

            modelBuilder.Entity("PortManagementSystem.DAL.Models.TempShip", b =>
                {
                    b.HasOne("PortManagementSystem.DAL.Models.TempTerminal", "tempTerminal")
                        .WithMany("tempShips")
                        .HasForeignKey("tempTerminalId")
                        .OnDelete(DeleteBehavior.Cascade);

                    b.HasOne("PortManagementSystem.DAL.Models.User", "tempUser")
                        .WithMany("tempShips")
                        .HasForeignKey("tempUserId")
                        .OnDelete(DeleteBehavior.Cascade)
                        .IsRequired();

                    b.Navigation("tempTerminal");

                    b.Navigation("tempUser");
                });

            modelBuilder.Entity("PortManagementSystem.DAL.Models.TempShipsWaiting", b =>
                {
                    b.HasOne("PortManagementSystem.DAL.Models.TempShip", "ship")
                        .WithMany()
                        .HasForeignKey("shipId")
                        .OnDelete(DeleteBehavior.Cascade)
                        .IsRequired();

                    b.Navigation("ship");
                });

            modelBuilder.Entity("PortManagementSystem.DAL.Models.TempTerminal", b =>
                {
                    b.Navigation("tempShips");
                });

            modelBuilder.Entity("PortManagementSystem.DAL.Models.Terminal", b =>
                {
                    b.Navigation("ships");
                });

            modelBuilder.Entity("PortManagementSystem.DAL.Models.User", b =>
                {
                    b.Navigation("ships");

                    b.Navigation("tempShips");
                });
#pragma warning restore 612, 618
        }
    }
}
